# Generated by Django 3.1.3 on 2022-07-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_subject', models.CharField(max_length=200)),
                ('movie_content', models.TextField()),
            ],
        ),
    ]
